### ISSUE TITLE
nsq_stat: why is egress negative

### ISSUE THREAD

**Issue by hklinux2010** [nsqio/nsq#1392]

**Comment by hklinux2010** [comment]
Who can explain ingress and egress

**Comment by ploxiln** [comment]
It looks like the only place "ingress" and "egress" are mentioned is in the `nsq_stat` utility: [github.com/HealthByRo/rodeo-drf-auth](https://github.com/nsqio/nsq/blob/v1.2.1/apps/nsq_stat/nsq_stat.go#L92)

It looks like, if the channel depth (queue depth) has increased by more than the total messages seen has increased, then egress will go negative. This could happen if messages were in-flight but then failed or timed-out and returned to the queue (and maybe also if there were deferred). It could possibly be fixed by factoring in-flight and deferred counts into these stats ...

**Comment by hklinux2010** [comment]
> It looks like the only place "ingress" and "egress" are mentioned is in the `nsq_stat` utility: [github.com/HealthByRo/rodeo-drf-auth](https://github.com/nsqio/nsq/blob/v1.2.1/apps/nsq_stat/nsq_stat.go#L92)
> 
> It looks like, if the channel depth (queue depth) has increased by more than the total messages seen has increased, then egress will go negative. This could happen if messages were in-flight but then failed or timed-out and returned to the queue (and maybe also if there were deferred). It could possibly be fixed by factoring in-flight and deferred counts into these stats ...

thanks，Your answer is of great help to me, but I still don't understand it. Can it be regarded as QPS? I want to count his speed. Negative numbers are a little difficult for me to understand. Can you talk about it more popularly

**Comment by ploxiln** [comment]
Every 2 seconds (by default), a couple things are measured, including:
  * total messages, which I will call `M`
  * main queue depth, which I will call `D`

"ingress" is based only on total messages. Let's call the latest measurement T1 and the previous measurement T0. So "ingress" is just `M1 - M0`, change in total messages.

"egress" is based on both total-messages, and main queue-depth: `(M1 - M0) - (D1 - D0)`. If the change in total messages is the same as the change in queue depth (`M1 - M0 = D1 - D0`) then no messages left the queue, so egress is 0. On the other hand, if total messages increased but depth remained the same (`M1 - M0 > 0` and `D1 - D0 = 0`), then egress = ingress. And it could be in between, if change in total messages is double the change in depth, then egress is half of ingress.

But, there is more than "main queue depth", there are also "in flight" and "deferred" messages, which are not counted in the main queue depth. "in flight" messages that timeout or fail are "requeued", but first they go into the "deferred" queue for a short time, before finally returning to the main queue to be delivered again. The simple equations above sort of assume that only "total messages" could add to the "main queue depth". But with "in flight" and "deferred" messages, these messages left the main queue some seconds ago, and then go back into the main queue some seconds later. So during that 2 second period when they go back into the main queue, the main queue depth goes up by more than total messages goes up (because these re-queued messages are not _new_ messages). And when that happens, `M1 - M0 < D1 - D0` so "egress" is negative `(M1 - M0) - (D1 - D0) < 0`.

This problem could be sort of "fixed" by changing the egress equation to something like `(M1 - M0) - ((D1 + F1 + E1) - (D0 + F0 + E0))` (where `F` is "in flight" and `E` is "deferred"). This would delay a message being considered "egress" until a consumer marks it "finish", but prevent egress from going negative. It's a bit subjective whether you want to call that egress, or have a separate "finished" stat which is similar to egress, but a little delayed, and never goes negative.

**Comment by hklinux2010** [comment]
Thank you for your patience. I see. Thank you very much！
